### ISSUE TITLE
Error while launching

### ISSUE THREAD

**Issue by KrokusAstra** [Silvertide7/pmmo_irons_compat#1]
Hi, i have this while trying to launch pmmo with pmmo irons compat, what should i do? Is this fixable?
![image](https://github.com/Silvertide7/pmmo_irons_compat/assets/172990355/cd10e3f2-8c2f-43d1-bdc5-ed9516767432)
Log, if you need 
[latest.log](https://github.com/user-attachments/files/15864113/latest.log)

I use both latest versions of Spellbook, Pmmo and your mod. Is if broken, or i'm installed incompatible mods besides those? (im just newbie with modpacks, sorry if something)

**Comment by Silvertide7** [comment]
Hey @KrokusAstra, thanks for the report! I actually just released a new version of this that fixes this issue yesterday. Make sure you are on the latest version of Iron's (1.20.1-3.1.7.1) and my mod (1.0.6). The project MMO mod version is more flexible. I just tested it on a heavily modded modpack and its working great! Let me know if something is still weird though.

**Comment by KrokusAstra** [comment]
Everything is working now! Thanks for your work! You did great! 😄

**Comment by Silvertide7** [comment]
Glad to hear it!
