### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by NeoStarWonV** [Silvertide7/pmmo_irons_compat#2]
[crash-2024-06-26_11.26.15-fml.txt](https://github.com/user-attachments/files/17041287/crash-2024-06-26_11.26.15-fml.txt)
I dont know why

**Comment by Silvertide7** [comment]
I don't see any reference to this mod in that crash file, why do you think this mod is responsible?

**Comment by Silvertide7** [comment]
Failure message: Mod thermal_cultivation requires cofh_core 11.0.0 or above, and below 11.1.0
		Currently, cofh_core is not installed
	Mod Version: 11.0.1
	Mod Issue URL: https://github.com/cofh/feedback
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by NeoStarWonV** [comment]
It's my fault，I upload the wrong crashreport

**Comment by NeoStarWonV** [comment]
[crash-2024-09-18_16.01.50-server.txt](https://github.com/user-attachments/files/17053340/crash-2024-09-18_16.01.50-server.txt)
