### ISSUE TITLE
This is the correct crash report，I upload a wrong report before

### ISSUE THREAD

**Issue by NeoStarWonV** [Silvertide7/pmmo_irons_compat#3]
[crash-2024-09-18_16.01.50-server.txt](https://github.com/user-attachments/files/17053408/crash-2024-09-18_16.01.50-server.txt)

**Comment by NeoStarWonV** [comment]
When I encountered the entity 'priest' in Iron Spell, I broke down

**Comment by NeoStarWonV** [comment]
version is 1.20.1

**Comment by NeoStarWonV** [comment]
iron spell and compat is all latest

**Comment by Silvertide7** [comment]
Ah okay, yeah that makes more sense! This is actually a known issue with Project MMO and Iron's. Here is the issue brought up before. https://github.com/Caltinor/Project-MMO-2.0/issues/498. It was decided that it likely couldn't be fixed until Iron's changed something on their side that they have yet to do so. It is not an interaction with this mod however. Trying to heal a Priest in your case triggered the Project MMO issue. I would read that other ticket to see if there has been anything that has helped, but i get that same error in my modpack as well unfortunately. It may be worth someday making a different addon to fix it.
